version: "3.8"
services:
  api1:  
    image: otocolobus:latest
    ports:
      - "5001:80"
  api2:  
    image: otocolobus:latest
    ports:
      - "5002:80"
  api3:  
    image: otocolobus:latest
    ports:
      - "5003:80"
  
  custom-nginx:
    build: 
      context: .
      dockerfile: Nginx/Dockerfile
    ports:
      - "5000:80"